"""added tables

Revision ID: eb4040fa92ab
Revises: 
Create Date: 2023-07-05 14:48:13.866065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4040fa92ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('announcement_id', sa.BIGINT(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('class_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('deleted', sa.CHAR(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_index(op.f('ix_announcement_announcement_id'), 'announcement', ['announcement_id'], unique=False)
    op.create_table('follow',
    sa.Column('follower_id', sa.BIGINT(), nullable=False),
    sa.Column('followee_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_index(op.f('ix_follow_followee_id'), 'follow', ['followee_id'], unique=False)
    op.create_index(op.f('ix_follow_follower_id'), 'follow', ['follower_id'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.BIGINT(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('receiver_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('deleted', sa.CHAR(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_message_id'), 'message', ['message_id'], unique=False)
    op.create_table('post',
    sa.Column('post_id', sa.BIGINT(), nullable=False),
    sa.Column('author_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('deleted', sa.CHAR(length=1), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_post_post_id'), 'post', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_message_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_follow_follower_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_followee_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index(op.f('ix_announcement_announcement_id'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
